setup:
  channels: &setup_channels
    - conda-forge
    - default
  dependencies: &setup_dependencies
    - python
    - pip
    - setuptools >=61.0
    - versioningit ~=2.0

production:
  channels: &production_channels
    - *setup_channels
  dependencies: &production_dependencies
    - python
    - pint

test:
  channels: &test_channels
    - *production_channels
  dependencies: &test_dependencies
    - *production_dependencies
    - pytest
    - pytest-cov
    - pytest-xdist
    - codecov
    - openmm
    - unyt

docs:
  channels: &docs_channels
    - *production_channels
  dependencies: &docs_dependencies
    - *production_dependencies
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - sphinx-remove-toctrees
    - sphinx-copybutton
    - myst-nb
    - openmm
    - unyt
    - jupyterlab


development:
  channels:
    - *production_channels
  dependencies:
    - *production_dependencies
    - *test_dependencies
    - *docs_dependencies
    - pyyaml
    - mamba

conda-build:
  channels:
    - *setup_channels
  dependencies:
    - *setup_dependencies
    - anaconda-client
    - conda-build

