package:
  name: pyunitwizard
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  host:
  - python >=3.11,<3.14
  - pip
  - setuptools >=68.0
  - versioningit >=3.0
  run:
  - python >=3.11,<3.14
  - numpy
  - pint
  - smonitor
  - depdigest
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library provides some useful methods to work with quantities

    '
  dev_url: https://github.com/uibcdf/pyunitwizard
  doc_url: https://uibcdf.org/pyunitwizard
