name: Build/upload conda packages ARM64

on:
  release:
    types: ['released', 'prereleased']

  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package to platform with Python ${{ matrix.python-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false  # do not cancel all in-progress jobs if any job variation fails
      matrix:
        python-version: ["3.11"]

    steps:
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup conda env
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/build_env.yaml
          environment-name: build
          condarc: |
            channels:
              - uibcdf
              - conda-forge
              - defaults
            channel_priority: strict

          create-args: >-
            python=${{ matrix.python-version }}

      - name: Info conda
        shell: bash -l {0}
        run: |
          micromamba info
          micromamba list

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: devtools/conda-build
          python-version: ${{ matrix.python-version }}
          mambabuild: false
          user: uibcdf
          label: auto
          platform_linux-64: false
          platform_osx-64: true
          platform_win-64: false
          token: ${{ secrets.ANACONDA_UIBCDF_TOKEN }}

