
name: Test installation on macos-latest

on:
  workflow_dispatch:

jobs:
  test:
    name: Python ${{ matrix.cfg.python-version }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: macos-latest, python-version: "3.9" }
          - { os: macos-latest, python-version: "3.10" }
          - { os: macos-latest, python-version: "3.11" }

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0    

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.cfg.python-version }}

    - name: Install micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: test
        condarc: |
          channels:
            - uibcdf
            - conda-forge
            - defaults
          channel_priority: strict

        create-args: >-
          python=${{ matrix.cfg.python-version }}

    - name: Info conda
      shell: bash -l {0}
      run: |
        micromamba activate test
        micromamba info
        micromamba list
        micromamba search pyunitwizard --channel uibcdf

    - name: Test installation
      run: |
        micromamba install -n test pyunitwizard
        python -c "import pyunitwizard; print(pyunitwizard.__version__)"
